Add ability to update existing alternative sets

diff --git a/install-jvm b/install-jvm
--- a/install-jvm
+++ b/install-jvm
@@ -31,18 +31,24 @@ help() {
     echo "                         mandatory"
     echo "  -t, --download-target  target name for the downloaded tar file"
     echo "                         -d must be set as well"
+    echo "  -u, --update           only update an existing alternative without installing"
+    echo "                         a new JVM. This effectively re-adds all executables in"
+    echo "                         the JVM's bin directory into the update-alternative"
+    echo "                         structure. Important if a JVM allows installation of"
+    echo "                         additional tools (e.g. GraalVM + native-image)"
     echo "  -x, --debug            does not serve any purpose at the moment"
     echo "                         will display more debug information in the future"
     echo ""
     echo "Examples:"
     echo "  install-jvm -d https://download.java.net/java/GA/jdk19.0.2/fdb695a9d9064ad6b064dc6df578380c/7/GPL/openjdk-19.0.2_linux-x64_bin.tar.gz -n jdk19.0.2"
     echo "  install-jvm -d https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.3.1/graalvm-ce-java19-linux-amd64-22.3.1.tar.gz -n graalvm-ce-java19-22.3.1"
+    echo "  install-jvm -u -n graalvm-ce-java19-22.3.1"
     echo ""
     echo "GitHub repository for the project: https://github.com/Visparu/unix-tools"
     echo "For questions or feature requests, please open an issue there."
 }
 
-x=n d=n t=n a=n e=n n=n j=n
+x=n d=n t=n a=n e=n n=n j=n u=n
 while [ $# -gt 0 ]; do
     case $1 in
         -x|--debug)
@@ -79,6 +85,10 @@ while [ $# -gt 0 ]; do
             JAVA_ALTERNATIVE_DIR="$2"
             shift 2
             ;;
+        -u|--update)
+            u=y
+            shift 1
+            ;;
         -h|-?|--help)
             help
             exit 0
@@ -92,14 +102,6 @@ while [ $# -gt 0 ]; do
     esac
 done
 
-# check for sudo permissions
-if [ $(id -u) -ne 0 ]; then
-    >&2 echo "Program must be executed with root privileges."
-    >&2 echo ""
-    help
-    exit 100
-fi
-
 # handle non-option arguments
 if [[ $# -ne 0 ]]; then
     >&2 echo "$0: No unnamed parameter expected."
@@ -108,20 +110,21 @@ if [[ $# -ne 0 ]]; then
     exit 2
 fi
 
-# check for required variables
-if [ -z ${DOWNLOAD_LOCATION+x} ] && [ -z ${ARCHIVE_LOCATION+x} ]; then
-    >&2 echo "A download location or an archive location is required (-d|--download or -a|--archive)."
+# check for sudo permissions
+if [ $(id -u) -ne 0 ]; then
+    >&2 echo "Program must be executed with root privileges."
     >&2 echo ""
     help
-    exit 3
+    exit 100
 fi
+
 if [ -z ${ALTERNATIVE_NAME+x} ]; then
     >&2 echo "An alternative name is required (-n|--name)."
     >&2 echo ""
     help
     exit 4
 fi
-
+  
 # substitute defaults
 if [ -z ${EXTRACT_DIR+x} ]; then
     EXTRACT_DIR=/tmp/install-jvm/extract
@@ -130,50 +133,63 @@ if [ -z ${JAVA_ALTERNATIVE_DIR+x}]; then
     JAVA_ALTERNATIVE_DIR=/usr/lib/jvm
 fi
 
-# download JDK tar file
-if [ ! -z ${DOWNLOAD_LOCATION+x} ]; then
-    if [ -z ${ARCHIVE_LOCATION+x} ]; then
-        ARCHIVE_LOCATION=$(basename $DOWNLOAD_LOCATION)
-    fi
-    wget $DOWNLOAD_LOCATION --quiet -O $ARCHIVE_LOCATION
-    if [ ! -f $ARCHIVE_LOCATION ]; then
-        >&2 echo "Download of JVM failed."
-        >&2 echo ""
-        exit 5
-    fi
+FULL_ALTERNATIVE_PATH=$JAVA_ALTERNATIVE_DIR/$ALTERNATIVE_NAME  
+  
+# check for update argument
+if [ $u != "y" ]; then
+
+  # check for pull location
+  if [ -z ${DOWNLOAD_LOCATION+x} ] && [ -z ${ARCHIVE_LOCATION+x} ]; then
+      >&2 echo "A download location or an archive location is required (-d|--download or -a|--archive)."
+      >&2 echo ""
+      help
+      exit 3
+  fi
+
+  # download JDK tar file
+  if [ ! -z ${DOWNLOAD_LOCATION+x} ]; then
+      if [ -z ${ARCHIVE_LOCATION+x} ]; then
+          ARCHIVE_LOCATION=$(basename $DOWNLOAD_LOCATION)
+      fi
+      wget $DOWNLOAD_LOCATION --quiet -O $ARCHIVE_LOCATION
+      if [ ! -f $ARCHIVE_LOCATION ]; then
+          >&2 echo "Download of JVM failed."
+          >&2 echo ""
+          exit 5
+      fi
+  fi
+  
+  # create extraction directory
+  mkdir -p $EXTRACT_DIR
+  if [ ! -z $(ls -A $EXTRACT_DIR) ]; then
+      >&2 echo "Extract directory is not empty."
+      >&2 echo ""
+      help
+      exit 6
+  fi
+  
+  # extract JDK files
+  tar -xzf $ARCHIVE_LOCATION -C $EXTRACT_DIR
+  
+  # delete archive if JDK was downloaded
+  if [ $d = "y" ]; then
+      rm $ARCHIVE_LOCATION
+  fi
+  
+  # move JDK to java-alternatives directory
+  rm -rf $FULL_ALTERNATIVE_PATH
+  mv $EXTRACT_DIR/$(ls -A $EXTRACT_DIR) $FULL_ALTERNATIVE_PATH
+  if [ ! -d $FULL_ALTERNATIVE_PATH ]; then
+      >&2 echo "Moving the JDK to the alternative path failed."
+      >&2 echo ""
+      help
+      exit 7
+  fi
+  
+  # remove extraction directory
+  rm -r $EXTRACT_DIR
+
 fi
-
-# create extraction directory
-mkdir -p $EXTRACT_DIR
-if [ ! -z $(ls -A $EXTRACT_DIR) ]; then
-    >&2 echo "Extract directory is not empty."
-    >&2 echo ""
-    help
-    exit 6
-fi
-
-# extract JDK files
-tar -xzf $ARCHIVE_LOCATION -C $EXTRACT_DIR
-
-# delete archive if JDK was downloaded
-if [ $d = "y" ]; then
-    rm $ARCHIVE_LOCATION
-fi
-
-FULL_ALTERNATIVE_PATH=$JAVA_ALTERNATIVE_DIR/$ALTERNATIVE_NAME
-
-# move JDK to java-alternatives directory
-rm -rf $FULL_ALTERNATIVE_PATH
-mv $EXTRACT_DIR/$(ls -A $EXTRACT_DIR) $FULL_ALTERNATIVE_PATH
-if [ ! -d $FULL_ALTERNATIVE_PATH ]; then
-    >&2 echo "Moving the JDK to the alternative path failed."
-    >&2 echo ""
-    help
-    exit 7
-fi
-
-# remove extraction directory
-rm -r $EXTRACT_DIR
 
 # gather binary files for alternatives
 BIN_DIRECTORY=$FULL_ALTERNATIVE_PATH/bin
